### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by gavin834** [jQAssistant/jQA-Idea-And-Support-Hub#3]
It would be useful to provide documentation to assist developers get the jQAssistant code up and running in a working environment.

It might be useful to have two variants of such information - one for people developing the product as part of their own work and another set for those who might want to contribute to the project in future.

The guide should include the minimum versions of tools such as JDK, Maven etc together with discussion of IDE configurations.

Over time, the guide could be expanded to bring in architectural details to assist developers in making the best updates, enhancements & extensions to jQAssistant in a manner in-keeping with the project as a whole.

**Comment by obfischer** [comment]
Sorry, we see that this is an important topic but currently we don't have the capacity for this.
