### ISSUE TITLE
programmatic creation of relation

### ISSUE THREAD

**Issue by aklemp** [jQAssistant/jQA-Idea-And-Support-Hub#8]
I would like to use the create-methods in class `Store` to programmatically create a relation between two nodes. Let's take the relation `DEPENDS_ON` as example. It defines a relation between two artifacts (in the sense of Maven artifact). The following code tries to create a relation between two packages.

```
Package a = store.find(PackageDescriptor.class, "foo.bar");
Package b = store.find(PackageDescriptor.class, "foo.baz");
store.create(a, DependsOnDescriptor.class, b);
```

I get the following error.

```
com.buschmais.xo.api.XOException: Cannot resolve entity type containing a relation of type 'DependsOnDescriptor'.
```

From a graph point-of-view a relation is somewhat general purpose. In this example, many things might depend on other things.

I see three possible solutions, all of which have some drawbacks.
- execute a Cypher query (no refactoring support because it is all in a String)
- extend the incoming/outgoing descriptors used in a relation descriptor (might make no sense, a package is no Maven artifact)
- create another DependsOnDescriptor with different incoming/outgoing descriptors (a lot of code)

Is there any other way? Would it be useful to introduce some more abstraction? E.g. introduce a `DependsOnIncomingDescriptor` and `DependsOnOutgoingDescriptor` that can be used in Maven artifacts, packages and anything else.

**Comment by obfischer** [comment]
Closing old ticket.
